# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClockifyToJira < Formula
  desc "Software to migrate time entries from clockify to jira."
  homepage "https://example.com/"
  version "0.7.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kruc/clockify-to-jira/releases/download/v0.7.0/clockify-to-jira_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "17daa30235abb172f3ec2995b0489acc486efebd5bd07b30de74b6de3ad1147f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kruc/clockify-to-jira/releases/download/v0.7.0/clockify-to-jira_0.7.0_Linux_x86_64.tar.gz"
    sha256 "f273a87c716079cdf3eab0ba053fc68cfe3280ce606306cddcfab64ec1fb4f92"
  end

  def install
    bin.install "clockify-to-jira"
  end

  def caveats; <<~EOS
    Run and read
  EOS
  end
end
