# This file was generated by GoReleaser. DO NOT EDIT.
class ClockifyToJira < Formula
  desc "Software to migrate time entries from clockify to jira."
  homepage "https://example.com/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kruc/clockify-to-jira/releases/download/v0.1.0/clockify-to-jira_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "8b966157383e3872fcd90a3ebbaf52231ebb8b14db6af34ecc24489fed7599df"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kruc/clockify-to-jira/releases/download/v0.1.0/clockify-to-jira_0.1.0_Linux_x86_64.tar.gz"
      sha256 "2779c37ae4ee13e6930bb4e1be76fa8872abd9098c836b1b740c072dea0e936a"
    end
  end

  def install
    bin.install "clockify-to-jira"
  end

  def caveats; <<~EOS
    Run and read
  EOS
  end
end
