# This file was generated by GoReleaser. DO NOT EDIT.
class Envsub < Formula
  desc "Parses templates using go templates"
  homepage "https://example.com/"
  version "0.0.4"

  if OS.mac?
    url "https://github.com/kruc/envsub/releases/download/v0.0.4/envsub_darwin.tar.gz"
    sha256 "bd8174517980c91110531ddd51e6620af4f2feaf2ed1bf02601596ff577627d0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kruc/envsub/releases/download/v0.0.4/envsub_linux.tar.gz"
      sha256 "328d67ea1b1659971de6d5ed8a7ceda6b63d748c08e6d7fa18ee73ddf4473d1a"
    end
  end

  def install
    bin.install "envsub"
  end

  def caveats; <<~EOS
    Run and read
  EOS
  end
end
