# This file was generated by GoReleaser. DO NOT EDIT.
class Envsub < Formula
  desc "Parses templates using go templates"
  homepage "https://example.com/"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kruc/envsub/releases/download/v0.0.3/envsub_darwin.tar.gz"
    sha256 "4c6df1293a3f37eedc82d44c97ff5299d32f21f532f72901b12188bb2a913032"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kruc/envsub/releases/download/v0.0.3/envsub_linux.tar.gz"
      sha256 "9c93aed60ab982f0a593d600126b44a9762ffbde32903b349bc007211fd4a3bb"
    end
  end

  def install
    bin.install "envsub"
  end

  def caveats; <<~EOS
    Run and read
  EOS
  end
end
