# This file was generated by GoReleaser. DO NOT EDIT.
class TogglToJira < Formula
  desc "Software to migrate time entries from toggl to jira."
  homepage "https://example.com/"
  version "0.7.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kruc/toggl-to-jira/releases/download/v0.7.1/toggl-to-jira_0.7.1_Darwin_x86_64.tar.gz"
    sha256 "86cae2c51fa72ecf1f1f76265c298547458a6106d96207ae70b1adbf578dab5c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kruc/toggl-to-jira/releases/download/v0.7.1/toggl-to-jira_0.7.1_Linux_x86_64.tar.gz"
      sha256 "2203966354c254210e39965df1b508650de0b952d8a932c230564896dfd86778"
    end
  end

  def install
    bin.install "toggl-to-jira"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
