# This file was generated by GoReleaser. DO NOT EDIT.
class TogglToJira < Formula
  desc "Software to migrate time entries from toggl to jira."
  homepage "https://example.com/"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kruc/toggl-to-jira/releases/download/v0.7.0/toggl-to-jira_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "22a959611b7b4178af1f14252437139f5e40f1d5a6287772575002b229bccf6e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kruc/toggl-to-jira/releases/download/v0.7.0/toggl-to-jira_0.7.0_Linux_x86_64.tar.gz"
      sha256 "010bdca147c4e44826337087572eeb6fea8e68d7c5f6c259703baa760b8da7d3"
    end
  end

  def install
    bin.install "toggl-to-jira"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
